version: '3'
services:
  app:
    build: ./client/.
    volumes:
      - ./client/:/app
      - node_volume:/app/node_modules
    ports:
      - "3000:3000"
    command: yarn run dev
    environment:
      NODE_ENV: "development"
      API_URL: "http://api:5432"

volumes:
  db_volume:
  node_volume:
  pycache_volume:
