apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: chainer-sample-ip
spec:
  rules:
    - host: ai.chainer-sample.net
      http:
        paths:
        - backend:
            serviceName: app-svc
            servicePort: 3000
